/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseSelect: typeof import('./src/components/common/Select/src/BaseSelect.vue')['default']
    BaseSlider: typeof import('./src/components/common/Slider/src/BaseSlider.vue')['default']
    DaysBackSlider: typeof import('./src/components/common/Slider/src/DaysBackSlider.vue')['default']
    Map: typeof import('./src/components/common/Map.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
